name: Build binary package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    name: Run tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install test dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            black
            isort
      - name: Check code with black
        run: black --check .
      - name: Check code with isort
        run: isort --profile black . --check-only

  build:
    name: Build installer
    runs-on: windows-latest
    needs:
      - test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install poetry
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          poetry

    - name: Install project dependencies
      run: |
        poetry install

    - name: Read version name
      id: version
      run: echo "::set-output name=version::${{ github.ref_name }}" | sed 's/::v/::/'

    - name: Build pyinstaller package
      run: |
        poetry run pyinstaller -D -w -i win64_logo.ico -n spicetify-beat-saber-backend --version-file win64_version_info.txt start.py

    - name: Add WiX Toolset to PATH
      shell: bash
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH

    - name: Build MSI installer
      shell: cmd
      run: |
        candle win64_installer.wxs -dVERSION=${{ steps.version.outputs.version }}
        light win64_installer.wixobj -ext WixUIExtension -out beatsaber-backend-${{ steps.version.outputs.version }}.msi

    - name: Upload workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: beatsaber-backend-${{ steps.version.outputs.version }}
        path: |
          dist/*
          *.msi
          *.wixpdb

    - name: Publish GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.msi
